name: Deploying ushauri_api test instance
on:
  push:
    branches: [ cicd ]
jobs:
  build:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
          -name: excecuting remote connection
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key : ${{ secrets.CICD_SECRET }}
            port : ${{ secrets.PORT }}
            script: |
                  git config --global --add safe.directory /apps/github-workflows/mhealth-apps/nishauri/      
                  cd /apps/github-workflows/mhealth-apps/nishauri/
                  git pull origin main
                  git status
                  docker-compose up -d

