name: Deploying ushauri_api test instance.
on:
  push:
    branches: [master]
jobs:
  build:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
      - name: excecuting remote connection
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key : ${{ secrets.CICD_SECRET }}
            port : ${{ secrets.PORT }}
            script: |
                  sudo rm -rf /apps/github-workflows/mhealth-apps/nishauri_api
                  sudo mkdir /apps/github-workflows/mhealth-apps/nishauri_api
                  sudo chown -R cicd2:cicd2 /apps/github-workflows/mhealth-apps/nishauri_api
                  git config --global --add safe.directory /apps/github-workflows/mhealth-apps/nishauri_api/
                  git clone https://github.com/palladiumkenya/nishauri_api.git /apps/github-workflows/mhealth-apps/nishauri_api
                  git status
                  cp /apps/dockerApps/nishauri_api-ssl/python.dockerfile /apps/github-workflows/mhealth-apps/nishauri_api/
                  cp /apps/dockerApps/nishauri_api-ssl/nginx.dockerfile /apps/github-workflows/mhealth-apps/nishauri_api/
                  cp /apps/dockerApps/nishauri_api-ssl/entrypoint.sh /apps/github-workflows/mhealth-apps/nishauri_api/
                  cp /apps/dockerApps/nishauri_api-ssl/requirements.txt /apps/github-workflows/mhealth-apps/nishauri_api/
                  cp /apps/dockerApps/nishauri_api-ssl/docker-compose.yml /apps/github-workflows/mhealth-apps/nishauri_api/
                  cp -r /apps/dockerApps/nishauri_api-ssl/docker /apps/github-workflows/mhealth-apps/nishauri_api/
                  cp /apps/dockerApps/nishauri_api-ssl/Nishauri_API/settings.py /apps/github-workflows/mhealth-apps/nishauri_api/Nishauri_API/
                  docker-compose down
                  docker-compose rm -f
                  docker-compose up -d --build
